name: strmine
main: Plugin.Main
description: test3
version: 1.1
api-version: 1.13
commands:
    gm:
        usage: 
    sethome:
        usage:
    home:
        usage:
    savespawn:
        usage:
    spawn:
        usage:
    tempmute:
        usage:
    ccreate:
        usage:
    pm:
        usage:
        aliases: [w,msg,tell]
    vanish:
        usage:
        aliases: [v]
    broadcast:
        usage:
        aliases: [bc,adv]
    sreload:
        usage:
        aliases: [srl]
    invcheck:
        usage:
        aliases: [ic]
    endercheck:
        usage:
        aliases: [ec]
    crash:
        usage:
    bedtp:
        usage: